# Generated by Django 5.1.5 on 2025-12-08 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_preferred_name', models.CharField(max_length=150)),
                ('user_business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_profile_image', models.ImageField(default='afan.jpg', upload_to='profile_pictures')),
                ('user_address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('user_address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('user_city', models.CharField(max_length=100)),
                ('user_province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=50)),
                ('user_postal_code', models.CharField(max_length=10)),
                ('user_website', models.URLField(blank=True, null=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
