# Generated by Django 5.1.5 on 2025-12-24 04:53

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.province')),
            ],
            options={
                'unique_together': {('province', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_type', models.CharField(choices=[('province', 'Entire Province'), ('cities', 'Selected Cities')], max_length=10)),
                ('cities', models.ManyToManyField(blank=True, to='users.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_preferred_name', models.CharField(max_length=150)),
                ('user_business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_profile_image', models.ImageField(default='no_profile_picture.jpg', upload_to=users.models.profile_image_path)),
                ('user_primary_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True)),
                ('user_secondary_phone', models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True)),
                ('user_business_phone', models.CharField(blank=True, help_text='Business contact phone number', max_length=20, null=True)),
                ('user_address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('user_address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('user_city', models.CharField(max_length=100)),
                ('user_province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=50)),
                ('user_postal_code', models.CharField(max_length=10)),
                ('user_website', models.URLField(blank=True, null=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subcategory')},
            },
        ),
    ]
