# Generated by Django 5.1.5 on 2025-12-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='no_profile_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
