# Generated by Django 5.1.5 on 2025-12-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_business_phone',
            field=models.CharField(blank=True, help_text='Business contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_primary_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_secondary_phone',
            field=models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True),
        ),
    ]
