# Generated by Django 5.1.5 on 2025-12-23 03:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_user_business_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(default='no_profile_picture.jpg', upload_to=users.models.profile_image_path),
        ),
    ]
