# Generated by Django 5.1.5 on 2025-12-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
